### PR TITLE
Now you can write quality with yt-dl supported links

### PR DESCRIPTION
**Pull request by magneto261290**
Please try to improve this, i am too noob. https://github.com/magneto261290/magneto-python-aria/blob/e9d935e6146e89d4687b06607977f33fd46468e4/bot/helper/mirror_utils/download_utils/youtube_dl_download_helper.py#L105

Example of writing quality (See screenshot)
ytdl quality example

### CODE REVIEW

**Comment by yashptel** [comment]
-downloads at 720p, if I mention anything higher than 720 (eg. 1080, 1440, 2160)
-downloads at 720p (1280x640 ), instead of the best quality available (which was 2160p. tried with MKBHD video) if the quality is not mentioned
-if quality passed is lower than 720, it works. For eg. 144, 360, etc. works and downloads correct res video.
So in short max video quality is capped at 720p. If anyone knows how to fix it. HELP!

**Comment by magneto261290** [comment]
> -downloads at 720p, if I mention anything higher than 720 (eg. 1080, 1440, 2160)
> -downloads at 720p (1280x640 ), instead of the best quality available (which was 2160p. tried with MKBHD video) if the quality is not mentioned
> -if quality passed is lower than 720, it works. For eg. 144, 360, etc. works and downloads correct res video.
> So in short max video quality is capped at 720p. If anyone knows how to fix it. HELP!

It's always an issue bcoz Bot's devs have choosen `best/bastvideo+bestaudio` instead of `bestvideo+bestaudio/best`.

so if you want maximum possible quality then go towatch.py file and edit Line no. 24 and 26. replace them with these lines
Line no. 24 -
`         qual = f'bestvideo[height<={qual}]+bestaudio/best[height<={qual}]'`

Line no. 26 -
`      qual = "bestvideo+bestaudio/best"`

Note :- Bot will show 0B size after uploading if you want tp download in max quality, so don't complain about that issue. and bot developers will give you proper reason, why you shouldn't use this quality setting.

**Comment by yashptel** [comment]
> > -downloads at 720p, if I mention anything higher than 720 (eg. 1080, 1440, 2160)
> > -downloads at 720p (1280x640 ), instead of the best quality available (which was 2160p. tried with MKBHD video) if the quality is not mentioned
> > -if quality passed is lower than 720, it works. For eg. 144, 360, etc. works and downloads correct res video.
> > So in short max video quality is capped at 720p. If anyone knows how to fix it. HELP!
> 
> It's always an issue bcoz Bot's devs have choosen `best/bestvideo+bestaudio` instead of `bestvideo+bestaudio/best`.
> 
> so if you want maximum possible quality then go towatch.py file and edit Line no. 24 and 26. replace them with these lines
> Line no. 24 -
> ` qual = f'bestvideo[height<={qual}]+bestaudio/best[height<={qual}]'`
> 
> Line no. 26 -
> ` qual = "bestvideo+bestaudio/best"`
> 
> Note :- Bot will show 0B size after uploading if you want tp download in max quality, so don't complain about that issue. and bot developers will give you proper reason, why you shouldn't use this quality setting.

Thanks a lot. It works.
And who cares about 0B when I can download in 2160p. Again thanks a lot.

**Comment by yuno74** [comment]
How about resolution with 1080 60fps

**Comment by yuno74** [comment]
Can I choose flac sound quality?

**Comment by magneto261290** [comment]
> Can I choose flac sound quality?

I don't think any site, which ytdl supports, gives flac quality.

**Pull request merged**
