### PR TITLE
Dockerfile: Move to alpine base

### PR DESCRIPTION
**Pull request by Akianonymus**
* 2x faster than Ubuntu base

### CODE REVIEW

**Comment by lzzy12** [comment]
Indeed alpine images are smaller in size and uses less resources than Ubuntu, however it comes at the cost of multiple limitations like many python libraries have to be built from source before they can be installed resulting in longer deployment times. Moreover, we are hit by this python bug if we don't use ubuntu image (even on debian image) https://bugs.python.org/issue38656

**Comment by Akianonymus** [comment]
> Indeed alpine images are smaller in size and uses less resources than Ubuntu, however it comes at the cost of multiple limitations like many python libraries have to be built from source before they can be installed resulting in longer deployment times. Moreover, we are hit by this python bug if we don't use ubuntu image (even on debian image) https://bugs.python.org/issue38656

Which python libraries ? 🤔

About deployment time, i did a realttime test comparing ubuntu and alpine base, and obviously alpine was faster.

No, we won't get hit by that bug because alpine latest python is 3.8, both in latest stable and edge.
See for yourself: https://pkgs.alpinelinux.org/packages?name=python*&branch=edge

**Comment by lzzy12** [comment]
3.7 or 3.8 doesn't matter here. The mimetype method depends on the os for extracting mimetypes. The bug still exists in 3.8. We have tried a lot before moving to ubuntu

**Comment by Akianonymus** [comment]
@lzzy12 Ok, i did some research for your statement, and actually, python version is the only thing matters here for Linux Systems, it is reported to be working on Mac and Windows ( info from the bug report page ).

Python versions above 3.6 are having this bug, so no, it doesn't depend on type of Linux OS as you suggested, but on the type of OS.

Yes, i tested this theory.

Why it's working in your Ubuntu docker configuration ? Well, it isn't rocket science, Ubuntu 18.04 includes python 3.6 as default python3 version, which is getting installed.

Now, i did some research on mimetypes, and python default mimetypes module is shit, no offense, but is kinda useless given it uses file format for mimetype output. Again, i am no python expert, just expressing my views, correct me if i am wrong.

I found another package, [python-magic](https://github.com/ahupp/python-magic), which legitimately guesses the file mimetype, rather than using the file format, working on alpine too ( probably everywhere ).

So, my suggestion is to use [python-magic](https://github.com/ahupp/python-magic) package to guess the mimetype.
And yes, that would be another commit, untill then, this commit is not merge-able yet.

Given the information i have provided, i don't think there should be any more obstructions for this pull request.

**Comment by Akianonymus** [comment]
Created python-magic PR

https://github.com/lzzy12/python-aria-mirror-bot/pull/31

**Comment by lzzy12** [comment]
You'll have to add locales back. This PR breaks mirror of files with non ASCII characters. (Try files with Chinese or Russian characters in their names)

**Comment by Akianonymus** [comment]
Ig this PR can be merged as nothing is faulty from thr docker side.

**Comment by lzzy12** [comment]
29ee3ac271a59b1eb54b79655a304549ca247d99

**Pull request closed without merging**
