### PR TITLE
[FIX] Switch SA after 'userRateLimitExceeded'

### PR DESCRIPTION
**Pull request by jagrit007**
FIX => ERROR - 'GoogleDriveHelper' object has no attribute 'service_account_count'

### CODE REVIEW

**Comment by lzzy12** [comment]
Hi, how do I reproduce this error without your patch?

**Comment by jagrit007** [comment]
Clone some folder of size more then daily quota (i.e above 750GB).

Also it's basic python :)

**Comment by a092devs** [comment]
> Clone some folder of size more then daily quota (i.e above 750GB).

Its not broken! I clone 2-3TB data often.

**Comment by jagrit007** [comment]
Merge it or not, IDC.

It ain't breaking anything but saving from any occurrence of "GoogleDriveHelper' object has no attribute 'service_account_count'"

**Comment by Akianonymus** [comment]
@jagrit007 Post a full log to verify your claims.

**Comment by ritik-gupta** [comment]
@lzzy12 this error occurs after cloning large files repeatedly. To reproduce this, try cloning some large folders (larger than daily quota of drive API).
And, even if it's not a issue on your side, it's a good python practice to initialise all the class variables properly. You should merge it and follow common python practices. He literally just initialised a class variable, no harm in merging.

@a092devs "often" doesn't help. Try cloning extensively for some time then you'll know. I can't understand your point anyways, just initialising a class variable doesn't break anything. It only improves the code in long run

**Comment by smartass08** [comment]
@ritik-gupta UserRateLimitExceeded occurs when you have exhausted your 750gb upload limit or when you are trying to write more files per minute than api supports, I don't think there isn't a case scenario where only certain large files will trigger it. Google api enables you to upload a single large file upto 5TB in one go so it won't cause you trouble of uploading only one type of file. This bot is well tested in our testing group and we haven't seen any attribute error regarding it.

 If we are uploading 2-3TB everyday then it already proves that the sa switching mechanism is working fine as intended to be. Instead of saying "merge or not" please provide any log which shows this error happening.

**Comment by lzzy12** [comment]
That variable is redundant. We are using local variable. The use of service_account_count in the upload() method is not needed. Will fix a patch soon. This is not accurate. Also I know my basics, you don't need to teach me :)

**Pull request closed without merging**
