### PR TITLE
Add Next and previous button in Status message

### PR DESCRIPTION
**Pull request by projectsrk**
whenever i add 30-40 downloads at the same time 
bot gives floodwait error
To avoid this error can you add next and previous inline buttons

### CODE REVIEW

**Comment by a092devs** [comment]
30-40 downloads? seriously?
you want google to terminate unlimited storage scheme before their announced time?

**Comment by projectsrk** [comment]
yes because i am using 16TB storage bot

**Comment by a092devs** [comment]
> yes because i am using 16TB storage bot

Still is a abuse considering google doesn't allow 16TB to mirror at once (even if you use Service Accounts, its massive abuse then)

**Comment by anasty17** [comment]
> > yes because i am using 16TB storage bot
> 
> Still is a abuse considering google doesn't allow 16TB to mirror at once (even if you use Service Accounts, its massive abuse then)

Maybe it's good to download many task in same, regardless about the size

**Comment by a092devs** [comment]
> > > yes because i am using 16TB storage bot
> > 
> > 
> > Still is a abuse considering google doesn't allow 16TB to mirror at once (even if you use Service Accounts, its massive abuse then)
> 
> Maybe it's good to download many task in same time, regardless of the size

**Comment by a092devs** [comment]
> > > yes because i am using 16TB storage bot
> > 
> > 
> > Still is a abuse considering google doesn't allow 16TB to mirror at once (even if you use Service Accounts, its massive abuse then)
> 
> Maybe it's good to download many task in same time, regardless of the size

I was talking about google drive's API abuse in the beginning, this is still a bad idea

**Comment by anasty17** [comment]
> > > > yes because i am using 16TB storage bot
> > > 
> > > 
> > > Still is a abuse considering google doesn't allow 16TB to mirror at once (even if you use Service Accounts, its massive abuse then)
> > 
> > Maybe it's good to download many task in same time, regardless of the size
> 
> I was talking about google drive's API abuse in the beginning, this is still a bad idea
> 
> 

You are right, but no one can stop the abuse ... if someone need to add more task maybe he will deploy another bot ... maybe 3 bots .. so who want to abuse will abuse anyway .. so 1 bot with 20 task best than 2 bots with 20 task ..

**Comment by lzzy12** [comment]
This should be an issue, not pull request as you've not sent an implementation

**Pull request closed without merging**
