### PR TITLE
HttpError 400 while using apostrophe in search

### PR DESCRIPTION
**Pull request by sumitbot**

### CODE REVIEW

**Comment by lzzy12** [comment]
This is not good. We should something like this https://stackoverflow.com/a/32310092

**Comment by smartass08** [comment]
Try this :- 

`>>> import json
>>> json.dumps("I'm")

'"I\'m"'`

**Comment by gautamajay52** [comment]
[Check this out !!](https://github.com/lzzy12/python-aria-mirror-bot/pull/140)

**Comment by lzzy12** [comment]
Closing this because a better PR already got merged https://github.com/lzzy12/python-aria-mirror-bot/pull/141

**Pull request closed without merging**
